language: python
python:
  - "2.7"
virtual_env:
  system_site_packages: true
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  coverage run --source=pytrustnfe setup.py nosetests
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libxmlsec1-dev libxslt-dev python-lxml
after_success:
  coveralls
